version: '3'
services:

  influxdb:
    image: influxdb:1.8.3
    container_name: ${PROJ_NAME}-influxdb
    #mem_limit: 2G # Can be set with docker-composer version '2'
    restart: unless-stopped
# Internal ports to be exposed to other linked services
# They will not be exposed to the host machine
#    expose:
#      - 8086
#      - 8083
#      - 2003
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - grafana-veeam
    volumes:
      - grafana-veeam-influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db
      - PROJ_NAME=${PROJ_NAME}

  grafana:
    image: grafana/grafana:7.3.5
    container_name: ${PROJ_NAME}-grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3002:3000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - grafana-veeam
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards
      - grafana-veeam-grafana_data:/var/lib/grafana
    environment:
      - INFLUXDB_DB=db
      - PROJ_NAME=${PROJ_NAME}

  collector:
    image: natke889/${PROJ_NAME}-collector:${TAG}
    container_name: ${PROJ_NAME}-collector
    restart: unless-stopped
    depends_on:
      - influxdb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - grafana-veeam
    volumes:
      - ./collector/veeam_enterprisemanager.sh:/app/veeam_enterprisemanager.sh
      - ./collector/veeam-cron:/etc/cron.d/veeam-cron
    environment:
      - INFLUXDB_DB=db
      - PROJ_NAME=${PROJ_NAME}
      - VEEAM_IP=${VEEAM_IP}
      - VEEAM_USER=${VEEAM_USER}
      - VEEAM_PASS=${VEEAM_PASS}

networks:
  grafana-veeam:
    external: false

volumes:
  grafana-veeam-grafana_data:
  grafana-veeam-influxdb_data: